[package]
name = "ncdu_output_viewer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = "*"
humansize = "*"
lazy_static = "*"
postgres = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[build-dependencies]
clap = "*"
clap_complete = "*"
